### PR TITLE
Moved the application server from Tomee to Quarkus

### PR DESCRIPTION
**Pull request by vv-b-s**
Modified some of the backend classes to work with Quarkus and updated the readme.

Problems: 
The frontend plugin has stopped working resulting in: ` No plugin found for prefix 'frontend' in the current project and in the plugin groups [org.apache.maven.plugins, org.codehaus.mojo] available from the repositories [local (/home/valentin/.m2/repository), central (https://repo.maven.apache.org/maven2)] `

### CODE REVIEW

**Comment by gochev** [comment]
well fix the problems :P

**Comment by gochev** [comment]
Please Fix all the issues and do not include new issues :) The only tasks is to move to Quarkus but keep everything as it is.

- e.g. everything should WORK as before.
- please use Mysql and not mariaDB (if we dont want H2 and we dont want it indeed you can do that in a prior PR if you want.)
- please update the readme to have quarkus:dev and etc.
- verify that all navigations articles twitter and etc are working as before after call api/test
- verify that ALL rest endpoints are working as before and requries JWT token as before.

**Comment by gochev** [comment]
to use MYSQL it should be something like this (not tested)

quarkus.datasource.url = jdbc:mysql://localhost:3306/bgjug?characterEncoding=utf8
quarkus.datasource.driver = org.mariadb.jdbc.Driver
quarkus.hibernate-orm.dialect=org.hibernate.dialect.MySQL5Dialect

**Comment by vv-b-s** [comment]
> to use MYSQL it should be something like this (not tested)
> 
> quarkus.datasource.url = jdbc:mysql://localhost:3306/bgjug?characterEncoding=utf8
> quarkus.datasource.driver = org.mariadb.jdbc.Driver
> quarkus.hibernate-orm.dialect=org.hibernate.dialect.MySQL5Dialect

I see you mention MySQL5Dialect as a dialect. Do we want MySql 5.x or use the latest available `8.0.17`

**Comment by gochev** [comment]
with 5.x I am sure it works :) and with this dialect which is already in the quarkus-mariadb-jdbc :) with 8.. I am not sure what version of JDBC and of Hibernate it requires.

**Comment by gochev** [comment]
there is also MySQL 55 and 57 dialects btw but I have never used them :)) I have tried hello world last week with Quarkuz and MySQL and it was working with this properties 99% sure ;) ..

**Comment by gochev** [comment]
Also please please please update the readme... since not everyone knows about the quarkus:dev... I am not sure is the -Pnative works? and so on..

**Comment by gochev** [comment]
@ivannov  pff this        quarkus-hibernate-orm-panache is so ugly... Article.Methods.. blah.. fck DAOs and Repositories.. is this really the proper way ? :( ... :) blqks

**Comment by ivannov** [comment]
> @ivannov pff this quarkus-hibernate-orm-panache is so ugly... Article.Methods.. blah.. fck DAOs and Repositories.. is this really the proper way ? :( ... :) blqks
> is this the STANDARD :))))))))))))))))

It is obvious that you didn't come to my Quarkus session for the JUG earlier. And I feel like one that sees in the future as I had a special joke for you regarding repositories

So, the thing is: do we really want to have repository classes that do not add business logic, but work as a collections of finders?

In Quarkus you can have both ways:

* You either make your entity extend `PanacheEntity` and get all the find/store methods there
* You make your repository implement `PanacheRepository` and have a completely meaningless class that is a collection of finder methods. That are not business logic!

So I asked @vv-b-s to do it the first way

Please, before you state your enormous Spring experience here as a reason, consider the following:

* The whole community mocks us Java devs as people who introduce meaningless levels of abstraction just because. To me repositories are meaningless level of abstraction if it is just an interface with some finder methods
* There is this Anemic domain model antipattern: https://www.martinfowler.com/bliki/AnemicDomainModel.html

**Pull request merged**
